name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push price_fetcher image
      uses: docker/build-push-action@v4
      with:
        context: ./price_fetcher
        push: true
        tags: shivamt064/price_fetcher:latest

    - name: Build and push lp_simulator image
      uses: docker/build-push-action@v4
      with:
        context: ./lp_simulator
        push: true
        tags: shivamt064/lp_simulator:latest
